codecov:
  notify:
    require_ci_to_pass: no
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 1
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    api:
      paths: app
    patch:
      default:
        threshold: 1
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

flags:
  frontend:
    paths:
      - app/
    assume: true
  api:
    paths:
      - app/
    assume: true
ignore:
  - app/**/test/**/*.py
  - app/**/tests/**/*.py
  - app/**/test_*.py
  - app/**/migrations/**/*.py
