name: codecov
on: [push]
jobs:
  build:
    
    runs-on: [ubuntu-latest]
    steps:
      - uses: codecov/codecov-action@v1.0.5
        name: codecov
        with:
          name: codecov
          # Repository upload token - get it from codecov.io
          token: ${{ secrets.CODECOV_TOKEN }} 
          # Path to coverage file to upload
          file:  ./coverage.xml # optional
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: unittests # optional
          # Specify the location of the .codecov.yml config file
          yml: ./codecov.yml # optional
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: true # optional
